spring:
  main:
# spring
    banner-mode: "off"
  output.ansi.enabled: ALWAYS
#DB connect
  datasource:
    url: jdbc:mysql://localhost:3306/blogStorage
    username: myRoot
    password: 147258369
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: validate
    show-sql: false
#liquibase
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

logging.level.: INFO

#settings for Blog:
blog.title: DevPub
blog.subTitle: Рассказы разработчиков
blog.phone: +7 951-408-60-62
blog.email: BlogDev@email.com
blog.copyright: Kazarnikov Aleksandr
blog.copyrightFrom: 2021