DROP TABLE IF EXISTS captcha_codes;
DROP TABLE IF EXISTS global_settings;
DROP TABLE IF EXISTS post_comments;
DROP TABLE IF EXISTS post_votes;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS tag2post;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS users;